import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <nav
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "flex-start",
            color: "white",
            background: "gray",
            opacity: "80%",
          }}
        >
          <Link
            style={{
              margin: "20px",
              fontSize: "30px", // Large text for logo effect
              fontWeight: "bold", // Bold text for emphasis
              color: "#cde7ca", // Dark color for contrast
              fontFamily: "Times New Roman", // Custom font (you can change to your preferred font)
              display: "inline-block", // Allow it to be styled like a block element
              padding: "10px 20px", // Add some padding for spacing around the text
              transition: "all 0.3s ease", // Smooth transition for hover effects
            }}
            href="/"
          >
            HOME GARDEN
          </Link>

          <Link style={{ margin: "20px" }} href="\posts">
            Posts
          </Link>
          <Link style={{ margin: "20px" }} href="\">
            Showcases
          </Link>
          <Link style={{ margin: "20px" }} href="\">
            DIY
          </Link>
        </nav>

        {children}
      </body>
    </html>
  );
}
